### ISSUE TITLE
[Coq] nanoyalla.zip unreachable

### ISSUE THREAD

**Issue by olaure01** [ComputerAidedLL/click-and-collect#167]
File [nanoyalla.zip](https://click-and-collect.linear-logic.org/download/nanoyalla.zip) not found.

**Comment by etiennecallies** [comment]
Hmmm... the url changed into https://click-and-collect.linear-logic.org/static/download/nanoyalla.zip and I forgot to update doc about it, my bad 😖 . It's fixed on master, but we need to redeploy, and I don't have the access any more.
